#!/bin/bash
### Job Name
#PBS -N mpi_job
### Project code
#PBS -A P54048000
#PBS -l walltime=0:05:00
#PBS -q regular
### Merge output and error files
#PBS -j oe
### Select 2 nodes with 36 CPUs each for a total of 72 MPI processes
#PBS -l select=2:ncpus=36:mpiprocs=36
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M cenlinhe@ucar.edu

### Run the executable
mpiexec_mpt dplace -s 1 ./real.exe


